specVersion: 0.0.1
description: Subquery node for Standard Opportunity testnet
repository: https://github.com/digitalnativeinc/standard-substrate.git
schema: ./schema.graphql
network:
  endpoint: wss://rpc.opportunity.standard.tech
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
