specVersion: 0.0.1
description: Subquery node for Opportunity Testnet
repository: https://github.com/digitalnativeinc/standard-subquery
schema: ./schema.graphql
network:
  endpoint: wss://rpc.opportunity.standard.tech:443
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
  types: {
      "AccountInfo": "AccountInfoWithTripleRefCount",
      "Address": "MultiAddress",
      "LookupSource": "MultiAddress",
      "XCurrencyId": {
        "chain_id": "ChainId",
        "currency_id": "Bytes"
      },
      "CurrencyIdOf": "CurrencyId",
      "CurrencyId": {
        "_enum": {
          "Token": "TokenSymbol"
        }
      },
      "TokenSymbol": {
        "_enum": [
          "OPT",
        ]
      },
      "AmountOf": "Amount",
      "Amount": "i128"
    }
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
